[package]
name = "csv_processing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.2"
io = "0.0.2"
serde = { version = "1.0", features = ["derive"] }
