[package]
name = "sha256_hash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.16.0"
ring = "0.16.20"
threadpool = "1.8.1"
walkdir = "2.3.3"
