[package]
name = "command_line"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arg = "0.4.1"
clap = { version = "4.3.11", features = ["derive"] }
